AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: false
